#!/usr/bin/env bash
#
# A bowtie2 wrapper
#
# Michael Chambers, 2014

# Initialize Hoffman environment
source /u/local/Modules/default/init/modules.sh
module load samtools
module load python/2.7.3

source ~/setup.sh

bam2wig.py $@