#!/usr/bin/env bash
USAGE='
Usage: phred33_to_64 [ -h ]

Converts a fastq file from Phred+64 (Solexa/Illumina 1.3+/1.5+)
to Phred+33 (Sanger/Illumina 1.8+)

Note: Requires gsed (MacPorts) as OSX sed will not do first~step

Michael Chambers, 2014-03-10
'

while getopts "h" opt; do
	case $opt in
		h)
			echo "$USAGE" >&2
			exit
			;;
		\?)
			echo "Flag not recognized: " >&2
			echo "$USAGE" >&2
			exit 2
			;;
	esac
done

if hash gsed 2>/dev/null; then
	gsed -e '4~4y/@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghi/!"#$%&'\''()*+,-.\/0123456789:;<=>?@ABCDEFGHIJ/'
else
	sed -e '4~4y/@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghi/!"#$%&'\''()*+,-.\/0123456789:;<=>?@ABCDEFGHIJ/'
fi