#!/usr/bin/env perl
use strict;
use Getopt::Std;
my $USAGE ='
Usage: qseqP2TH_from_file.pl  -h arg_file

Calls bin/qseqPipeline_2_tophat_htseq.sh with the following parameters

qseqPipeline_2_tophat_htseq.sh IN_DIR SCRATCH_OUT ANALYSIS_OUT LANE INDEX

Obtains paramaters from argument file. One Lane/index pair per line. File formatted as follows: (tab-sep)

in_dir scratch_dir analysis_dir lane index

Comments (prepended by #) are allowed.

Michael Chambers, 2012
';

our($opt_h);
getopts('h');
&usage if($opt_h);
&usage if($#ARGV < 0);
sub usage{
	print STDERR $USAGE;
	exit 2;
}


my $file = shift;
my $task = $ENV{'SGE_TASK_ID'};

open FILE, "< $file";
my $current_line=0;
for(<FILE>){
	next if(/^#/);
	my @line = split;
	next if($#line != 4);
	$current_line++;
	if($current_line == $task){
		print STDERR "@@@ LOG: Beginning analysis of LINENUM: $current_line SGE_TASK_ID: $task ARGS: $_ " . `date` . "\n";
		my ($in_dir, $scratch, $analysis, $lane, $index) = @line;
		my $command = "qseqPipeline_2_tophat_htseq.sh $in_dir $scratch $analysis $lane $index";
		print STDERR "@@@ LOG: Calling command $command\n";
		`$command`
	}
}