#!/usr/bin/env bash
# qseqToFastQ.sh
# Converts a qseq file to a fastq file
# Input may be piped in (plain text) or supplied as an arg(s)
# Args may be plain or gzipped
# Output is to stdout
# Michael Chambers, 2014-03-10


# If no arguments assume pipe
if [ $# -eq 0 ]; then
	awk '
		BEGIN {count = 0}
		{
			count++
			mylen = length($9);
			print "\@" $2 "\:" $3 "\:" $4 "\:" $5 "\:" $6 "\:" count "\#" mylen;
			print $9;
			print "\+";
			print $10;
		}' | tr '.' 'N'

# Else take from command line
else
	while (( $# )); do
		cmd=cat
		if [[ $1 =~ .gz$ ]]; then
			cmd=zcat
		fi
		$cmd < $1 | awk '
			BEGIN {count = 0}
			{
				count++
				mylen = length($9);
				print "\@" $2 "\:" $3 "\:" $4 "\:" $5 "\:" $6 "\:" count "\#" mylen;
				print $9;
				print "\+";
				print $10;
			}' | tr '.' 'N'
	shift
	done
fi
